FROM openjdk:8-jre-alpine

RUN apk --update add tar bash libstdc++ bind-tools && \
    rm -rf /tmp/* /var/cache/apk/*

COPY ureplicator.tgz /
RUN tar -zxf  ureplicator.tgz -C / && \
    rm -f ureplicator.tgz


COPY config /uReplicator/config
COPY bin /uReplicator/bin
RUN chmod +x /uReplicator/bin/*.sh

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


ENTRYPOINT [ "/entrypoint.sh" ]
